remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Site Settings
locale                   : "en"
title                    : "Shinaoka Group"
name                     : "Hiroshi Shinaoka"

# This will require each of these plugins automatically.
plugins:
  - jekyll-include-cache
